### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by DimonYoing** [thebigcrafter/KygekClearConsole#1]
The plugin was uploaded to the server, but I write the clearconsole command and nothing happens

**Comment by KygekDev** [comment]
What is your server's operating system?

**Comment by DimonYoing** [comment]
android

**Comment by DimonYoing** [comment]
android

**Comment by KygekDev** [comment]
Android is untested, so I'm going to put this issue as "To Be Reproduced"

**Comment by DimonYoing** [comment]
When will it be on android?

**Comment by ghost** [comment]
> When will it be on android?

Currently, this plugin is **only** works for Windows, Linux and OS X. Android is not a OS made for running any servers so I think it's too hard to clear an console but I think this plugin also works with Termux (untested)
